export const AUTH = {
  GETTER: {
    IS_AUTHED: 'AUTH/GETTER/IS_AUTHED',
    SIGN_IN_ERROR: 'AUTH/GETTER/SIGN_IN_ERROR',
    SIGN_IN_FIELDS: 'AUTH/GETTER/SIGN_IN_FIELDS',
    SIGN_IN_IS_LOADING: 'AUTH/GETTER/SIGN_IN_IS_LOADING',
    FORGOT_FIELDS: 'AUTH/GETTER/FORGOT_FIELDS',
    FORGOT_IS_LOADING: `AUTH/GETTER/FORGOT_IS_LOADING`,
    FORGOT_STATUS: `AUTH/GETTER/FORGOT_STATUS`,
    FORGOT_ERROR: `AUTH/GETTER/FORGOT_ERROR`,
    REGISTRATION_FIELDS: `AUTH/GETTER/REGISTRATION_FIELDS`,
    REGISTRATION_IS_LOADING: `AUTH/GETTER/REGISTRATION_IS_LOADING`,
    REGISTRATION_ERROR: `AUTH/GETTER/REGISTRATION_ERROR`
  },
  MUTATION: {
    RESET_SIGN_IN: 'AUTH/MUTATION/RESET_SIGN_IN',
    CHANGE_FIELD_SIGN_IN: `AUTH/MUTATION/CHANGE_FIELD_SIGN_IN`,
    SET_LOADING_SIGN_IN: `AUTH/MUTATION/SET_LOADING_SIGN_IN`,
    SET_ERROR_SIGN_IN: `AUTH/MUTATION/SET_ERROR_SIGN_IN`,
    SET_IS_AUTHED: `AUTH/MUTATION/SET_AUTHED_IN`,
    RESET_FORGOT: `AUTH/MUTATION/RESET_FORGOT`,
    CHANGE_FIELD_FORGOT: `AUTH/MUTATION/CHANGE_FIELD_FORGOT`,
    SET_ERROR_FORGOT: `AUTH/MUTATION/SET_ERROR_FORGOT`,
    SET_LOADING_FORGOT: `AUTH/MUTATION/SET_LOADING_FORGOT`,
    SET_FORGOT_STATUS: `AUTH/MUTATION/SET_FORGOT_STATUS`,
    RESET_REGISTRATION: `AUTH/MUTATION/RESET_REGISTRATION`,
    CHANGE_FIELD_REGISTRATION: `AUTH/MUTATION/CHANGE_FIELD_REGISTRATION`,
    SET_LOADING_REGISTRATION: `AUTH/MUTATION/SET_LOADING_REGISTRATION`,
    SET_ERROR_REGISTRATION: `AUTH/MUTATION/SET_ERROR_REGISTRATION`
  },
  ACTION: {
    SUBMIT_SIGN_IN: `AUTH/ACTION/SUBMIT_SIGN_IN`,
    SUBMIT_PASSWORD_RECOVERY: `AUTH/ACTION/SUBMIT_PASSWORD_RECOVERY`,
    LOGOUT: 'AUTH/ACTION/LOGOUT',
    SUBMIT_REGISTRATION: 'AUTH/ACTION/SUBMIT_REGISTRATION'
  }
}

export const WALLET = {
  GETTER: {
    LIST_FOR_SIDEBAR: 'WALLET/GETTER/LIST_FOR_SIDEBAR',
    WALLETS_COUNT: `WALLET/GETTER/WALLETS_COUNT`,
    TABLE_FOR_SETTINGS: `WALLET/GETTER/TABLE_FOR_SETTINGS`,
    GET_WALLETS: `WALLET/GETTER/WALLETS`,
    GET_WALLET_BY_CODE: `WALLET/GETTER/GET_WALLET_BY_CODE`,
    GET_INITIALIZING: `WALLET/GETTER/GET_INITIALIZING`,
    GET_WALLET_BY_ID: `WALLET/GETTER/GET_WALLET_BY_ID`
  },
  MUTATION: {
    SET_WALLET_LIST: `WALLET/MUTATION/SET_WALLET_LIST`,
    REMOVE_WALLET: `WALLET/MUTATION/REMOVE_WALLET`
  },
  ACTION: {
    LOAD_WALLET_LIST: `WALLET/ACTION/LOAD_CURRENCY_LIST`,
    REMOVE_WALLET: `WALLET/ACTION/REMOVE_WALLET`
  }
}

export const PROFILE = {
  GETTER: {
    LIST_REWARD: `PROFILE/GETTER/LIST_REWARD`,
    USER: `PROFILE/GETTER/USER`
  },
  MUTATION: {
    SET_PROFILE_DATA: `PROFILE/MUTATION/SET_PROFILE_DATA`,
    SET_LIST_REWARD: `PROFILE/MUTATION/SET_LIST_REWARD`
  },
  ACTION: {
    LOAD_PROFILE_DATA: `PROFILE/ACTION/LOAD_PROFILE_DATA`,
    CHANGE_PASSWORD: `PROFILE/ACTION/CHANGE_PASSWORD`,
    CHANGE_PROFILE_DATA: `PROFILE/ACTION/CHANGE_PROFILE_DATA`,
    DELETE_PROFILE: `PROFILE/ACTION/DELETE_PROFILE`
  }
}

export const NETWORK = {
  GETTER: {
    LIST_FOR_ADD_MODAL: `NETWORK/GETTER/LIST_FOR_ADD_MODAL`
  },
  MUTATION: {
    SET_IS_LOADING: `NETWORK/MUTATION/SET_IS_LOADING`,
    SET_NETWORK_LIST: `NETWORK/MUTATION/SET_NETWORK_LIST`
  },
  ACTION: {
    LOAD_NETWORKS: `NETWORK/ACTION/LOAD_NETWORKS`
  }
}

export const REWARD = {
  GETTER: {
    GET_REWARD_FOR_TABLE: `REWARD/GETTER/GET_REWARD_FOR_TABLE`,
    IS_LOADING: `REWARD/GETTER/IS_LOADING`,
    GET_CURRENCY: `REWARD/GETTER/GET_CURRENCY`,
    GET_SORT_SETTINGS: `REWARD/GETTER/GET_SORT_SETTINGS`,
    GET_REWARDS_AND_BALANCE_WITH_CURRENCIES: `REWARD/GETTER/GET_REWARDS_AND_BALANCE_WITH_CURRENCIES`,
    GET_TOTAL_REWARDS: `REWARD/GETTER/GET_TOTAL_REWARDS`
  },
  MUTATION: {
    SET_IS_LOADING: `REWARD/MUTATION/SET_IS_LOADING`,
    SET_REWARDS: `REWARD/MUTATION/SET_REWARDS`,
    SET_BALANCE: `REWARD/MUTATION/SET_BALANCE`,
    SET_CURRENCY: `REWARD/MUTATION/SET_CURRENCY`,
    SET_SORT_SETTINGS: `REWARD/MUTATION/SET_SORT_SETTINGS`
  },
  ACTION: {
    LOAD_REWARDS: `REWARD/ACTION/LOAD_REWARDS`
  }
}

export const TRANSACTION = {
  GETTER: {
    GET_TRANSACTIONS_FOR_TABLE: `TRANSACTION/GETTER/GET_TRANSACTIONS_FOR_TABLE`,
    GET_CHART_OPTIONS: `TRANSACTION/GETTER/GET_CHART_OPTIONS`,
    GET_TABLE_OPTIONS: `TRANSACTION/GETTER/GET_TABLE_OPTIONS`,
    GET_CHART_DATA: `TRANSACTION/GETTER/GET_CHART_DATA`,
    GET_PREVIEW_CHART_DATA: `TRANSACTION/GETTER/GET_PREVIEW_CHART_DATA`,
    IS_CHART_LOADING: `TRANSACTION/GETTER/IS_CHART_LOADING`,
    IS_TRANSACTIONS_LOADING: `TRANSACTION/GETTER/IS_TRANSACTIONS_LOADING`
  },
  MUTATION: {
    SET_TRANSACTIONS: `TRANSACTION/MUTATION/SET_TRANSACTIONS`,
    SET_CHART_DATES: `TRANSACTION/MUTATION/SET_CHART_DATES`,
    SET_CHART_DATA: `TRANSACTION/MUTATION/SET_CHART_DATA`,
    SET_PREVIEW_CHART_DATA: `TRANSACTION/MUTATION/SET_PREVIEW_CHART_DATA`,
    SET_IS_TRANSACTIONS_LOADING: `TRANSACTION/MUTATION/SET_IS_TRANSACTIONS_LOADING`,
    SET_IS_CHART_LOADING: `TRANSACTION/MUTATION/SET_IS_CHART_LOADING`,
    SET_TABLE_LIMIT: `TRANSACTION/MUTATION/SET_TABLE_LIMIT`,
    SET_TABLE_PAGE: `TRANSACTION/MUTATION/SET_TABLE_PAGE`,
    SET_CHART_CURRENCY: `TRANSACTION/MUTATION/SET_CHART_CURRENCY`
  },
  ACTION: {}
}

export const ADD_NEW_ADDRESS = {
  GETTER: {
    GET_FIELDS: `ADD_NEW_ADDRESS/GETTER/GET_FIELDS`,
    IS_OPEN: `ADD_NEW_ADDRESS/GETTER/IS_OPEN`,
    IS_LOADING: `ADD_NEW_ADDRESS/GETTER/IS_LOADING`,
    IS_ERROR: `ADD_NEW_ADDRESS/GETTER/IS_ERROR`
  },
  MUTATION: {
    SET_IS_LOADING: `ADD_NEW_ADDRESS/MUTATION/SET_IS_LOADING`,
    CHANGE_FIELD: `ADD_NEW_ADDRESS/MUTATION/CHANGE_FIELD`,
    SET_MODAL_OPEN: `ADD_NEW_ADDRESS/MUTATION/SET_MODAL_OPEN`,
    SET_IS_ERROR: `ADD_NEW_ADDRESS/MUTATION/SET_IS_ERROR`
  },
  ACTION: {
    SUBMIT: `ADD_NEW_ADDRESS/ACTION/SUBMIT`
  }
}

export const UI = {
  GETTER: {
    CONFIRM_DELETE: `UI/GETTER/CONFIRM_DELETE`,
    CONFIRM_IS_LOADING: `UI/GETTER/CONFIRM_IS_LOADING`,
    GET_CONFIRM_MESSAGE: `UI/GETTER/GET_CONFIRM_MESSAGE`
  },
  MUTATION: {
    SET_CONFIRM_IS_OPEN: `UI/MUTATION/SET_CONFIRM_IS_OPEN`,
    SET_CONFIRM_FUNCTION: `UI/MUTATION/SET_CONFIRM_FUNCTION`,
    SET_CONFIRM_LOADING: `UI/MUTATION/SET_CONFIRM_LOADING`,
    SET_CONFIRM_MESSAGE: `UI/MUTATION/SET_CONFIRM_MESSAGE`
  },
  ACTION: {
    CONFIRM: `UI/ACTION/CONFIRM`
  }
}

export const CURRENCY_OVERALL = {
  GETTER: {
    GET_CURRENT_CURRENCY_CODE: `CURRENCY_OVERALL/GETTER/GET_CURRENT_CURRENCY_CODE`,
    IS_DATA_LOADING: `CURRENCY_OVERALL/GETTER/IS_DATA_LOADING`
  },
  MUTATION: {
    SET_CURRENT_CURRENCY_CODE: `CURRENCY_OVERALL/MUTATION/SET_CURRENT_CURRENCY_CODE`,
    SET_IS_DATA_LOADING: `CURRENCY_OVERALL/MUTATION/SET_IS_DATA_LOADING`
  },
  ACTION: {
    LOAD_CHART_AND_TRANSACTIONS: `CURRENCY_OVERALL/ACTION/LOAD_CHART_AND_TRANSACTIONS`,
    UPDATE_CHART_DATA: `CURRENCY_OVERALL/ACTION/UPDATE_CHART_DATA`,
    LOAD_TRANSACTIONS_PAGE: `CURRENCY_OVERALL/ACTION/LOAD_TRANSACTIONS_PAGE`
  }
}

export const CURRENCY_WALLET = {
  GETTER: {
    GET_CURRENT_WALLET_ID: `CURRENCY_WALLET/GETTER/GET_CURRENT_WALLET_ID`,
    IS_DATA_LOADING: `CURRENCY_WALLET/GETTER/IS_DATA_LOADING`
  },
  MUTATION: {
    SET_CURRENT_WALLET_ID: `CURRENCY_WALLET/MUTATION/SET_CURRENT_WALLET_ID`,
    SET_IS_DATA_LOADING: `CURRENCY_WALLET/MUTATION/SET_IS_DATA_LOADING`
  },
  ACTION: {
    LOAD_CHART_AND_TRANSACTIONS: `CURRENCY_WALLET/ACTION/LOAD_CHART_AND_TRANSACTIONS`,
    UPDATE_CHART_DATA: `CURRENCY_WALLET/ACTION/UPDATE_CHART_DATA`,
    LOAD_TRANSACTIONS_PAGE: `CURRENCY_WALLET/ACTION/LOAD_TRANSACTIONS_PAGE`
  }
}

export const WALLET_OVERALL = {
  GETTER: {
    IS_OVERALL_LOADING: `WALLET_OVERALL/GETTER/IS_OVERALL_LOADING`
  },
  MUTATION: {
    SET_IS_LOADING: `WALLET_OVERALL/GETTER/SET_IS_LOADING`
  },
  ACTION: {
    LOAD_DATA: `WALLET_OVERALL/ACTION/LOAD_DATA`,
    UPDATE_CHART_DATA: `WALLET_OVERALL/ACTION/UPDATE_CHART_DATA`,
    LOAD_TRANSACTIONS_PAGE: `WALLET_OVERALL/ACTION/LOAD_TRANSACTIONS_PAGE`
  }
}

export const TOPBAR = {
  GETTER: {
    GET_TYPE: `TOPBAR/GETTER/GET_TYPE`,
    GET_TYPE_LIST: `TOPBAR/GETTER/GET_TYPE_LIST`,
    GET_TYPE_LABEL: `TOPBAR/GETTER/GET_TYPE_LABEL`
  },
  MUTATION: {
    SET_TYPE: `TOPBAR/MUTATION/SET_TYPE`
  },
  ACTION: {
    SET_TYPE_AND_RELOAD_DATA: `TOPBAR/ACTION/SET_TYPE_AND_RELOAD_DATA`
  }
}
export const POLLS = {
  GETTER: {
    GET_POLLS_FOR_LIST: `POLLS/GETTER/GET_POLLS_FOR_LIST`,
    GET_IS_LOADING: `POLLS/GETTER/GET_IS_LOADING`,
    GET_CURRENT_TIME: `POLLS/GETTER/GET_CURRENT_TIME`
  },
  MUTATION: {
    SET_POLLS: `POLLS/MUTATION/SET_POLLS`,
    SET_IS_LOADING: `POLLS/MUTATION/SET_IS_LOADING`,
    UPDATE_CURRENT_TIME: `POOLS/MUTATION/UPDATE_CURRENT_TIME`
  },
  ACTION: {
    LOAD_POLLS: `POLLS/ACTION/LOAD_POLLS`
  }
}
